#!/bin/bash
while :; do
    case "$1" in
	"--help"|"-h")
	    if [ -z "$help" ]; then
		[ "$debug" = "true" ] && echo "Showing help menu"
		help="true"
	    fi
	    ;;
 
        "--debug"|"-d")
            if [ -z "$debug" ]; then
                [ "$debug" = "true" ] && echo "Enabling debug output"
                debug="true"
            else
                echo "debug has already been enabled!"
            fi
            ;;

        "--nsfw"|"-n")
            if [ -z "$imgtype" ]; then
                [ "$debug" = "true" ] && echo "Getting a nsfw image"
                imgtype="nsfw"
            else
                echo "$imgtype images were already chosen! Please only specify either sfw, nsfw or gif!"
            fi
            ;;
	"--gif"|"-g")
            if [ -z "$imgtype" ]; then
                [ "$debug" = "true" ] && echo "Getting a nsfw image"
                imgtype="gif"
            else
                echo "$imgtype images were already chosen! Please only specify either sfw, nsfw or gif!"
            fi
            ;;

        "--sfw"|"-s")
            if [ -z "$imgtype" ]; then
                [ "$debug" = "true" ] && echo "Getting a sfw image"
                imgtype="sfw"
            else
                echo "$imgtype images were already chosen! Please only specify either sfw, nsfw or gif!"
            fi
            ;;
        *)
            if [ -z "$1" ]; then
                break
            fi
            echo "Could not interpret parameter '$1'."
            ;;
    esac
    shift
done
if [ ! -d ./nekos ]; then
        mkdir ./nekos
fi
if [ ! -d ./nekos/nsfw ]; then
        mkdir ./nekos/nsfw
fi
if [ ! -d ./nekos/sfw ]; then
        mkdir ./nekos/sfw
fi
if [ ! -d ./nekos/gifs ]; then
        mkdir ./nekos/gifs
fi
if [ "$help" = "true" ]; then
	echo "Help menu:"
	echo "--help | -h	Shows this menu"
	echo "--debug | -d	Enables debug output"
	echo "--nsfw | -n	Downloads nsfw image"
	echo "--sfw | -s	Downloads sfw image"
	echo "--gif | -g	Downloads (nsfw) gif image"
fi
if [ "$imgtype" = "nsfw" ]; then
        imgurl=("https://nekos.life/api/v2/img/cum_jpg" "https://nekos.life/api/v2/img/lewd" "https://nekos.life/api/v2/img/pussy_jpg" "https://nekos.life/api/v2/img/lewdk" "https://nekos.life/api/v2/img/erokemo" "https://nekos.life/api/v2/img/blowjob" "https://nekos.life/api/v2/img/lewdkemo" "https://nekos.life/api/v2/img/tits" "https://nekos.life/api/v2/img/eroyuri" "https://nekos.life/api/v2/img/yuri" "https://nekos.life/api/v2/img/hentai")
	dir=./nekos/nsfw
elif [ "$imgtype" = "sfw" ]; then
        imgurl=("https://nekos.life/api/v2/img/neko")
	dir=./nekos/sfw
elif [ "$imgtype" = "gif" ]; then
        imgurl=("https://nekos.life/api/v2/img/feetg" "https://nekos.life/api/v2/img/cum" "https://nekos.life/api/v2/img/bj" "https://nekos.life/api/v2/img/spank" "https://nekos.life/api/v2/img/solog" "https://nekos.life/api/v2/img/Random_hentai_gif" "https://nekos.life/api/v2/img/pussy" "https://nekos.life/api/v2/img/pwankg" "https://nekos.life/api/v2/img/nsfw_neko_gif")
        dir=./nekos/gifs
else
	[ "$debug" = "true" ] && echo "Not downloading image"
fi

if [ "$imgtype" ]; then
    imgurlr=${imgurl[RANDOM%${#imgurl[@]}]}
    [ "$debug" = "true" ] && echo "Using api at url $imgurlr"
    url=$(curl -fsSL "$imgurlr" | jq -r ".url")
    [ "$debug" = "true" ] && echo "Using image at url $url"
    cd "$dir"
    curl -O "$url" > /dev/null 2>&1
fi
